/*product 테이블*/
-- create table tb_product (
--         count integer,
--         price integer,
--         product_id bigint generated by default as identity,
--         user_id bigint not null,
--         name varchar(255) not null,
--         primary key (product_id)
-- )
--     comment on column tb_product.count is '재고수량'
--     comment on column tb_product.price is '가격'
--     comment on column tb_product.name is'상품명'
--
-- /*user 테이블*/
-- create table tb_user (
--      user_id bigint generated by default as identity,
--      name varchar(255) not null,
--      primary key (user_id)
-- )
--     comment on column tb_user.name is '사용자 이름'

INSERT INTO tb_user (name) VALUES ('user1');
INSERT INTO tb_user (name) VALUES ('user2');

INSERT INTO tb_product (name, price, count) VALUES ('연필', 500, 10);
INSERT INTO tb_product (name, price, count) VALUES ('지우개', 100, 100);
INSERT INTO tb_product (name, price, count) VALUES ('공책', 5000, 50);